build:
    image: docker:latest
    stage: build
    services:
        - docker:dind
    before_script:
        - export ZOU_VERSION=0.10.18
        - export BASE_NAME=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}/zou
        - export IMAGE_NAME=${BASE_NAME}:${ZOU_VERSION}
        - export BUILD_NAME=${IMAGE_NAME}-layered
        - apk add --update py-pip && pip install docker-squash
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - docker build --build-arg ZOU_VERSION=${ZOU_VERSION} --pull -t "${BUILD_NAME}" .
        - docker-squash -t "${IMAGE_NAME}" -c "${BUILD_NAME}"
        - docker tag "${IMAGE_NAME}" "${BASE_NAME}:latest"
        - docker push "${BASE_NAME}"
    only:
        - zou